### ISSUE TITLE
Error messages?

### ISSUE THREAD

**Issue by luckyxero46** [DevMiser/Edison#1]
Hi-  Sorry if this is not the correct place to put this, but I tried your project and am getting the following messages.  

Do you know what could be wrong?  I've never used a backpack before so do you think it's that?  It was plugged in like your diagram stated.

Thanks for any help!
Elly

===========start===========
pi@raspberrypi:~/Edison $ python3 Edison.py
Traceback (most recent call last):
  File "/home/pi/Edison/Edison.py", line 46, in <module>
    i2c = board.I2C()
  File "/home/pi/.local/lib/python3.9/site-packages/board.py", line 409, in I2C
    return busio.I2C(SCL, SDA)
  File "/home/pi/.local/lib/python3.9/site-packages/busio.py", line 37, in __init__
    self.init(scl, sda, frequency)
  File "/home/pi/.local/lib/python3.9/site-packages/busio.py", line 162, in init
    raise ValueError(
ValueError: No Hardware I2C on (scl,sda)=(3, 2)
Valid I2C ports: ((1, 3, 2), (0, 1, 0), (10, 45, 44))
===========end===========

**Comment by luckyxero46** [comment]
Scratch that last comment.  I figured it out.  The i2C interface was not turned on.  

Maybe you can add that to your instructions?

Turn on I2C interface.
Raspberry Pi> Preferences> Raspberry Pi Configuration > Interfaces > I2C switch to on.

**Comment by DevMiser** [comment]
Done.  Thank you.
